spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "Pronto lalala"
  default-value: "World"
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'